// action 타입
export const RECIEVE_API_DATA = 'RECIEVE_API_DATA';
export const RECIEVE_API_TOTAL_DATA = 'RECIEVE_API_TOTAL_DATA';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_TO_FAVORITE = 'REMOVE_TO_FAVORITE';
export const CURRENT_MY_REGION = 'CURRENT_MY_REGION';
export const CURRENT_TOTAL_REGION = 'CURRENT_TOTAL_REGION';
export const PAGE_UPDATE = 'PAGE_UPDATE';
